"""Update Task

Revision ID: 2e6534c51a15
Revises: f551d6d4dd40
Create Date: 2025-10-18 00:03:28.641240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add this import

# revision identifiers, used by Alembic.
revision: str = '2e6534c51a15'
down_revision: Union[str, Sequence[str], None] = 'f551d6d4dd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM type for reusability
priority_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create the new ENUM type in the database first
    priority_enum.create(op.get_bind(), checkfirst=False)

    # 2. Alter the column, telling PostgreSQL how to convert the old integers
    op.alter_column('tasks', 'priority',
        existing_type=sa.INTEGER(),
        type_=priority_enum,
        existing_nullable=False,
        postgresql_using="CASE priority WHEN 1 THEN 'low' WHEN 2 THEN 'medium' WHEN 3 THEN 'high' END::priority")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # To downgrade, we convert back to INTEGER.
    op.alter_column('tasks', 'priority',
        existing_type=priority_enum,
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="CASE priority WHEN 'low' THEN 1 WHEN 'medium' THEN 2 WHEN 'high' END")

    # Finally, drop the ENUM type from the database
    priority_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###